version: '3.1'
services:
  stats-server:
    build: statistic/
    image: 'statistic'
    container_name: explore_with_me_statistic_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/exploreWithMeStatistic

  stats-db:
    image: postgres:14-alpine
    container_name: explore_with_me_statistic_db
    ports:
      - "6543:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=exploreWithMeStatistic
      - POSTGRES_USER=exploreWithMe
      - POSTGRES_PASSWORD=exploreWithMe

  ewm-service:
    build: main/
    image: 'main'
    container_name: explore_with_me_main_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - statistic.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/exploreWithMe

  ewm-db:
    image: postgres:14-alpine
    container_name: explore_with_me_main_db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=exploreWithMe
      - POSTGRES_USER=exploreWithMe
      - POSTGRES_PASSWORD=exploreWithMe
